id = 0

# A commitlog read will pull full segment. Make sure that a segment isn't
# too big as async tcp writes readiness of one connection might affect tail
# latencies of other connection. Not a problem with preempting runtimes
[router]
id = 0
max_connections = 10010
max_outgoing_packet_count = 200
max_segment_size = 104857600
max_segment_count = 10

[v4.1]
name = "v4-1"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 10
     # tls config for rustls
     [v4.1.tls]
     capath = "./tls-certs/ca.cert.pem"
     certpath = "./tls-certs/server.cert.pem"
     keypath = "./tls-certs/server.key.pem"
     [v4.1.connections]
     connection_timeout_ms = 60000
     throttle_delay_ms = 0
     max_payload_size = 20480
     max_inflight_count = 100
     max_inflight_size = 1024
